### ISSUE TITLE
Identify error produced by test case in revision ee93f030:

### ISSUE THREAD

**Issue by allenerocha** [allenerocha/pysky#9]
2020-11-30 20:36:22,113 [INFO] Retrieving data for tonight's moon...
Traceback (most recent call last):
  File "C:\Users\William\PycharmProjects\pysky\venv\Scripts\pysky-script.py", line 33, in <module>
    sys.exit(load_entry_point('pysky==0.9.9', 'console_scripts', 'pysky')())
  File "c:\users\william\pycharmprojects\pysky\venv\lib\site-packages\pysky\__main__.py", line 13, in main
    invoke()
  File "c:\users\william\pycharmprojects\pysky\venv\lib\site-packages\pysky\core.py", line 47, in invoke
    gen_moon_data()
  File "c:\users\william\pycharmprojects\pysky\venv\lib\site-packages\pysky\core.py", line 477, in gen_moon_data
    illumination, phase = query()
  File "c:\users\william\pycharmprojects\pysky\venv\lib\site-packages\pysky\moonquery.py", line 28, in query
    for item in data["2"]:
TypeError: list indices must be integers or slices, not str

**Comment by allenerocha** [comment]
Will need to update the backend to look for the second element in the jArray:
var jArray= [["<b>November 29<\/b>","11%\n","Sun Angle: 0.54058026531573","Sun Distance: 147536183.29263","Moon Distance: 404836.02949655","Moon Age: 3.239200614848","Moon Angle: 0.49194771114535","Waxing Crescent","November 29"],["<b>November 30<\/b>","18%\n","Sun Angle: 0.54066956029474","Sun Distance: 147511816.76387","Moon Distance: 405489.91732104","Moon Age: 4.1310891289452","Moon Angle: 0.49115440259472","Waxing Crescent","November 30"],["<b>December 1<\/b>","Illumination: <span>26%\n<\/span>","Sun Angle: <span>0.54","Sun Distance: <span>147,<\/span>488,<\/span>081.42","Moon Distance: <span>405,<\/span>169.76","Moon Age: <span>5.02","Moon Angle: <span>0.49","Waxing Crescent","December 1, 2000","December","Phase: <span>Waxing Crescent<\/span>","December 1"],["<b>December 2<\/b>","35%\n","Sun Angle: 0.54084126594969","Sun Distance: 147464984.88416","Moon Distance: 403875.27596167","Moon Age: 5.9054139516098","Moon Angle: 0.49311797466627","Waxing Crescent","December 2"],["<b>December 3<\/b>","44%\n","Sun Angle: 0.54092361693534","Sun Distance: 147442534.6038","Moon Distance: 401639.45933911","Moon Age: 6.7991174569752","Moon Angle: 0.49586302707336","Waxing Crescent","December 3"]];
